# Generated by Django 4.2.5 on 2024-01-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("banner", models.ImageField(upload_to="site/")),
                ("caption", models.TextField()),
            ],
        ),
    ]
